version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: flight-postgres
    environment:
      POSTGRES_USER: flight_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: flight_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # airflow:
  # kafka:
  # superset:
